name: CI
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request: null

jobs:
  build_test:
    strategy:
      matrix:
        host: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 20, 21]
    name: build_test - ${{ matrix.host }} - node@${{ matrix.node }}
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - name: Install
        run: pnpm install --side-effects-cache=false
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build:all
      - name: Test
        run: pnpm test
