name: CI 
permissions:
  contents: write
  id-token: write
on:
  push:
    branches:
      - *
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
  pull_request: null

jobs:
  build:
    strategy:
      matrix:
        host: [ubuntu-latest, macos-latest, windows-latest]
        node: [18, 20, 21]
    name: Build
    runs-on: ${{ matrix.host  }} - ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }} 
          cache: pnpm
      - name: Install and build
        run: pnpm install && pnpm build:all
      - name: Test
        run: pnpm install && pnpm build:all
  
