name: Publish
permissions:
  contents: write
  id-token: write
on:
  push:
    branches: 
      - 'chore/ci'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        ref: chore/ci
    - uses: pnpm/action-setup@v3
      with:
        version: 10
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install and build
      run: pnpm install && pnpm build:all
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          .
          !**/node_modules
        if-no-files-found: error

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          check-latest: true
          cache: pnpm
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: List packages
        run: ls -R packages/**
        shell: bash
      - name: Publish
        run: |
          npm config set provenance true
          npm config set access public
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          pnpm publish -r --filter "{packages/**}" --access public --no-git-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

