name: Publish
permissions:
  contents: write
  id-token: write
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install and build
        run: pnpm install && pnpm build:all
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: .
          if-no-files-found: error

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: pnpm
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: List packages
        run: cd artifact && ls -R packages/**
        shell: bash
      - name: Set npm
        run: |
          npm config set provenance true
          npm config set access public
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Enter prerelease
        if: ${{ contains(github.ref, 'beta') }}
        run: pnpm changeset pre enter beta
      - name: Exit prerelease
        if: ${{ ! contains(github.ref, 'beta') }}
        run: pnpm changeset pre exit 
      - name: Publish 
        uses: changesets/action@v1
        with:
          commit: "chore: bump versions"
          title: "chore: bump versions"
          publish: pnpm publish -r --filter "{packages/**}" --access public --no-git-checks 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

